services:
  ios_notacookbook_backend:
    image: marijndemul16/iosnotacookbook.backend:latest
    ports:
      - "3600:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./decisive-bazaar-450812-n8-247d0b92397c.json:/app/decisive-bazaar-450812-n8-247d0b92397c.json:ro

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
    restart: unless-stopped